# Site settings
title: "백엔드 개발자 이승재"
description: "이력서"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "이승재"
resume_title:                   "기록을 많이 하는 개발자"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dyctdy@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "010-8831-8367"
# resume_contact_address:         "주소"

resume_header_contact_info:     "dyctdy@gmail.com"
display_header_contact_info:    "true" # 전화번호, 메일 공개여부

resume_header_intro: "<p>
                        기록을 좋아하는 백엔드 개발자 이승재입니다.<br>
                        공부했던 기록, 그리고 업무중 발생했던 이슈를 정리하기위해 블로그를 운영하고 있습니다.<br>
                        개인 프로젝트나 개발 커뮤니티 활동 등을 통해 다양한 개발 경험을 즐기고 있습니다.<br>
                        추가적으로 끊임없이 무언가를 추가적으로 적용해보려고 개발 서적을 꾸준히 읽고 있습니다.<br>
                        개발을 함에 있어서 클린코드와 코드리뷰 문화를 항상 생각해왔기 때문에
                        NEXTSTEP에서 주관하는 TDD, Clean Code with Java 12기를 이수하였습니다.<br>
                      </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false # recognition.yml
resume_section_links:           true # links.yml
resume_section_associations:    true # association.yml
resume_section_interests:       false # interests.yml

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/lsj8367"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/%EC%8A%B9%EC%9E%AC-%EC%9D%B4-146778214/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://lsj8367.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
